#requires -version 5
<#
  Pool Launcher (prototype) — терминальный пикер пулов поверх pool.manifest.json.
  Поток: выбрать пул (fzf, сортировка по недавности) -> выбрать режим/роли ->
         сгенерировать разовый Warp tab-config (команды только в выбранных панелях) ->
         открыть Warp. Цикл. Синглтон. Esc — шаг назад по уровням (роли -> режим -> пулы -> выход).
         Доднятие в пустой панели — через Ctrl-Shift-R (Warp Workflows).

  Запуск:        powershell -NoProfile -ExecutionPolicy Bypass -File launch-pool.ps1
  Самопроверка:  ... -File launch-pool.ps1 -SelfTest   (без fzf и без Warp: дискаверинг + генерация TOML)
#>
[CmdletBinding()]
param(
  [string[]]$Roots = @('<workspace-root>'),
  [switch]$SelfTest,
  [switch]$NoSingleton
)

$ErrorActionPreference = 'Stop'

# --- UTF-8 в консоли: нужно и для пайпа в fzf, и для кириллицы ---
try {
  [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
  [Console]::InputEncoding  = [System.Text.Encoding]::UTF8
} catch {}
$OutputEncoding = [System.Text.Encoding]::UTF8

$Here   = Split-Path -Parent $MyInvocation.MyCommand.Path
$Fzf    = Join-Path $Here 'bin\fzf.exe'
$StateD = Join-Path $Here '.state'
$MruPath = Join-Path $StateD 'mru.json'
$PidF   = Join-Path $StateD 'owner.pid'
$TabCfg = Join-Path $env:APPDATA 'warp\Warp\data\tab_configs'

# ---------- генерация TOML (тестируется в -SelfTest, без fzf) ----------
function Build-Panes {
  param($node, $manifest, $selected, $focusOwner, [ref]$counter, $acc)
  $n = $counter.Value; $counter.Value = $counter.Value + 1
  $id = "p$n"
  if ($node.PSObject.Properties.Name -contains 'role') {
    $owner = $node.role
    $role  = $manifest.roles | Where-Object { $_.owner -eq $owner } | Select-Object -First 1
    $block = @('[[panes]]', ('id = "{0}"' -f $id), 'type = "terminal"', ("directory = '{0}'" -f $manifest.root))
    if (($selected -contains $owner) -and $role) {
      $bat = '{0}\{1}' -f $manifest.root, $role.bat
      $block += ("commands = ['cmd /c `"{0}`"']" -f $bat)
    } elseif ($role) {
      # Пустая (незапущенная) панель: одна строка-подсказка — как поднять эту роль
      # (Warp Workflow по Ctrl-Shift-R или прямой запуск .bat). ASCII — чтобы не ловить кодовую страницу cmd.
      $bat  = '{0}\{1}' -f $manifest.root, $role.bat
      $hint = 'cmd /c echo [{0}] empty pane -- launch: cmd /c "{1}"  or Warp Workflows Ctrl-Shift-R search {0}' -f $owner, $bat
      $block += ("commands = ['{0}']" -f $hint)
    }
    if ($owner -eq $focusOwner) { $block += 'is_focused = true' }
    [void]$acc.Add([pscustomobject]@{ N = $n; Text = ($block -join "`r`n") })
  } else {
    $childIds = @()
    foreach ($c in $node.children) {
      $childIds += (Build-Panes -node $c -manifest $manifest -selected $selected -focusOwner $focusOwner -counter $counter -acc $acc)
    }
    $kids  = ($childIds | ForEach-Object { '"{0}"' -f $_ }) -join ', '
    $block = @('[[panes]]', ('id = "{0}"' -f $id), ('split = "{0}"' -f $node.split), ('children = [{0}]' -f $kids))
    [void]$acc.Add([pscustomobject]@{ N = $n; Text = ($block -join "`r`n") })
  }
  return $id
}

# Auto-layout when a manifest has no explicit `layout`: lead first, pack roles into columns of <=2 panes,
# columns laid out left-to-right (respects "max 2 vertical, grow right"). Returns a node tree like manifest.layout.
function Build-AutoLayout($roles) {
  $ordered = @(@($roles | Where-Object { $_.lead }) + @($roles | Where-Object { -not $_.lead }))
  $leaves  = @($ordered | ForEach-Object { [pscustomobject]@{ role = $_.owner } })
  $cols = @()
  for ($i = 0; $i -lt $leaves.Count; $i += 2) {
    if ($i + 1 -lt $leaves.Count) {
      $cols += ,([pscustomobject]@{ split = 'vertical'; children = @($leaves[$i], $leaves[$i + 1]) })
    } else {
      $cols += ,($leaves[$i])
    }
  }
  if ($cols.Count -le 1) { return $leaves[0] }
  return [pscustomobject]@{ split = 'horizontal'; children = $cols }
}

function New-PoolToml {
  param($m, $selected)
  $counter = 0
  $acc = New-Object System.Collections.ArrayList
  $focus = if ($selected -contains $m.lead) { $m.lead } else { @($selected)[0] }
  $layout = if (($m.PSObject.Properties.Name -contains 'layout') -and $m.layout) { $m.layout } else { Build-AutoLayout $m.roles }
  [void](Build-Panes -node $layout -manifest $m -selected $selected -focusOwner $focus -counter ([ref]$counter) -acc $acc)
  $head = @('# Auto-generated by Pool Launcher (prototype). Do not edit by hand.',
            ('name  = "{0}"' -f $m.title),
            ('title = "{0}"' -f $m.slug))
  if ($m.color) { $head += ('color = "{0}"' -f $m.color) }
  $body = ($acc | Sort-Object N | ForEach-Object { $_.Text }) -join "`r`n`r`n"
  return ($head -join "`r`n") + "`r`n`r`n" + $body + "`r`n"
}

# ---------- дискаверинг манифестов (рекурсивно до глубины 3; тяжёлые/служебные папки мимо) ----------
function Get-ManifestsUnder($dir, $depth, $acc) {
  $mf = Join-Path $dir 'pool.manifest.json'
  if (Test-Path $mf) { [void]$acc.Add($mf) }
  if ($depth -le 0) { return }
  Get-ChildItem -Path $dir -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch '^(node_modules|\.git|\.bus|\.warp|\.state|\.inbox)$' } |
    ForEach-Object { Get-ManifestsUnder $_.FullName ($depth - 1) $acc }
}
function Find-Manifests {
  $acc = New-Object System.Collections.ArrayList
  foreach ($root in $Roots) {
    if (-not (Test-Path $root)) { continue }
    Get-ChildItem -Path $root -Directory -ErrorAction SilentlyContinue |
      Where-Object { $_.Name -notmatch '^(node_modules|\.git|\.bus|\.warp|\.state|\.inbox)$' } |
      ForEach-Object { Get-ManifestsUnder $_.FullName 3 $acc }
  }
  $acc | Select-Object -Unique
}

function Read-Json($path) { Get-Content -Raw -Encoding UTF8 $path | ConvertFrom-Json }

# Control/meta сессии (Launcher, DevOps-оркестратор) — не проектные пулы: описаны централизованно в
# launcher-овском control.json (массив manifest-подобных объектов), чтобы не писать в чужие зоны (.devops и пр.).
function Get-ControlPools {
  $cf = Join-Path $Here 'control.json'
  if (-not (Test-Path $cf)) { return @() }
  try { return @((Get-Content -Raw -Encoding UTF8 $cf | ConvertFrom-Json)) } catch { return @() }
}

function Load-Mru {
  if (Test-Path $MruPath) { try { return (Get-Content -Raw -Encoding UTF8 $MruPath | ConvertFrom-Json) } catch { return $null } }
  return $null
}
function Save-Mru($obj) { ($obj | ConvertTo-Json -Depth 5) | Set-Content -Path $MruPath -Encoding UTF8 }
function Mru-Time($mru, $slug) {
  if ($mru -and ($mru.PSObject.Properties.Name -contains $slug)) { try { return [datetime]$mru.$slug } catch { } }
  return [datetime]::MinValue
}

# ---------- fzf ----------
function Invoke-Fzf {
  param([string[]]$Items, [string]$Prompt, [string]$Header, [switch]$Multi)
  $a = @('--no-sort','--no-unicode','--layout=reverse','--height=70%','--border','--info=inline','--cycle',
         '--prompt', ($Prompt + ' '), '--header', $Header)
  if ($Multi) { $a += @('--multi','--marker=*') }
  $sel = $Items | & $Fzf @a
  return $sel
}

# ---------- self-test ----------
if ($SelfTest) {
  Write-Host "== SelfTest: дискаверинг ==" -ForegroundColor Cyan
  $paths = Find-Manifests
  $paths | ForEach-Object { Write-Host "  manifest: $_" }
  foreach ($p in $paths) {
    $m = Read-Json $p
    Write-Host "`n== $($m.slug) :: режим 'Ведущий' (только $($m.lead)) ==" -ForegroundColor Cyan
    Write-Host (New-PoolToml $m @($m.lead))
    Write-Host "== $($m.slug) :: режим 'Полный' (все $($m.roles.Count)) ==" -ForegroundColor Cyan
    Write-Host (New-PoolToml $m @($m.roles.owner))
  }
  Write-Host "`n== auto-layout demo (5 ролей без явного layout -> 3 колонки) ==" -ForegroundColor Cyan
  $demo = [pscustomobject]@{ slug='demo'; title='Demo'; project='auto'; root='D:\x'; color='cyan'; lead='r1';
    roles=@(
      [pscustomobject]@{owner='r1';title='R1';bat='r1.bat';lead=$true},
      [pscustomobject]@{owner='r2';title='R2';bat='r2.bat'},
      [pscustomobject]@{owner='r3';title='R3';bat='r3.bat'},
      [pscustomobject]@{owner='r4';title='R4';bat='r4.bat'},
      [pscustomobject]@{owner='r5';title='R5';bat='r5.bat'}) }
  Write-Host (New-PoolToml $demo @($demo.roles.owner))
  Write-Host ("== control.json: загружено записей = " + (@(Get-ControlPools).Count) + " ==") -ForegroundColor Cyan
  return
}

# ---------- синглтон ----------
$created = $false
$mtx = New-Object System.Threading.Mutex($true, 'Global\PoolLauncherProto', [ref]$created)
if (-not $NoSingleton -and -not $created) {
  if (Test-Path $PidF) {
    $opid = (Get-Content $PidF -ErrorAction SilentlyContinue | Select-Object -First 1)
    $p = Get-Process -Id $opid -ErrorAction SilentlyContinue
    if ($p -and $p.MainWindowHandle -ne 0) {
      try {
        Add-Type -Name Win -Namespace Native -MemberDefinition @'
[DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);
[DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr h, int n);
'@ -ErrorAction SilentlyContinue
        [Native.Win]::ShowWindow($p.MainWindowHandle, 9) | Out-Null
        [Native.Win]::SetForegroundWindow($p.MainWindowHandle) | Out-Null
      } catch {}
    }
  }
  Write-Host "Pool Launcher уже запущен — окно выведено на передний план." -ForegroundColor Yellow
  Start-Sleep -Milliseconds 900
  exit 0
}
New-Item -ItemType Directory -Force -Path $StateD | Out-Null
Set-Content -Path $PidF -Value $PID -Encoding ASCII

# ---------- главный цикл (Esc = шаг назад по уровням) ----------
try {
  while ($true) {                                   # уровень ПУЛА
    $manifests = @()
    foreach ($p in (Find-Manifests)) { try { $m = Read-Json $p; $manifests += $m } catch {} }
    $manifests += (Get-ControlPools)
    if (-not $manifests) { Write-Host "Манифесты пулов не найдены под: $($Roots -join ', ')" -ForegroundColor Red; break }

    $mru = Load-Mru
    # обычные пулы — по недавности; архивные — отдельной группой внизу, с пометкой [архив]
    $normal = @($manifests | Where-Object { -not $_.archive } | Sort-Object @{ Expression = { Mru-Time $mru $_.slug }; Descending = $true }, @{ Expression = { $_.title } })
    $arch   = @($manifests | Where-Object { $_.archive } | Sort-Object @{ Expression = { $_.title } })
    $pools = @($normal) + @($arch)
    $map = [ordered]@{}
    foreach ($pl in $pools) {
      $when = Mru-Time $mru $pl.slug
      $pre  = if ($pl.archive) { '[архив] ' } else { '' }
      $tag  = if ($when -eq [datetime]::MinValue) { '' } else { '   (последний: ' + $when.ToString('dd.MM HH:mm') + ')' }
      $map[($pre + ('{0}  —  {1}{2}' -f $pl.title, $pl.project, $tag))] = $pl
    }
    $poolSel = Invoke-Fzf -Items ([string[]]$map.Keys) -Prompt 'Пул>' -Header 'Выбор пула  |  Enter — далее, Esc — выход'
    if (-not $poolSel) { break }                    # Esc на пуле -> выход из пикера
    $pool = $map[[string]$poolSel]

    while ($true) {                                 # уровень ДЕЙСТВИЯ (пульт: запустить / завершить / борд)
      $actItems = @(
        '[Запустить] — поднять сессии пула',
        '[Завершить] — handoff -> гашение -> compact (в отдельном окне)',
        '[Борд]      — открыть/поднять живую доску пула'
      )
      $actSel = Invoke-Fzf -Items $actItems -Prompt 'Действие>' -Header ('Пул: ' + $pool.title + '  |  Esc — назад к пулам')
      if (-not $actSel) { break }                   # Esc на действии -> назад к списку пулов

      # ----- [Борд]: открыть живую доску (idempotent .bat -> board-window.ps1) -----
      if ($actSel.StartsWith('[Борд')) {
        if (-not $pool.root) { Write-Host 'Это control-сессия без пула — доски нет.' -ForegroundColor Yellow; Start-Sleep -Milliseconds 900; continue }
        $boardBat = Join-Path $pool.root ('board-' + $pool.slug + '.bat')
        if (Test-Path $boardBat) { Start-Process -FilePath $boardBat }
        else {
          $bw = Join-Path (Split-Path $Here -Parent) 'pool-bus\board-window.ps1'
          Start-Process 'powershell' -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$bw,'-BusRoot',(Join-Path $pool.root '.bus'))
        }
        Write-Host ('Доска "{0}" открыта.' -f $pool.title) -ForegroundColor Green
        Start-Sleep -Milliseconds 700
        continue                                     # назад к выбору действия
      }

      $isShutdown = $actSel.StartsWith('[Завершить')
      if ($isShutdown -and -not $pool.root) { Write-Host 'Control-сессия: завершение через контроллер не поддерживается.' -ForegroundColor Yellow; Start-Sleep -Milliseconds 900; continue }
      $verb = if ($isShutdown) { 'Завершить' } else { 'Запустить' }

      while ($true) {                               # уровень РЕЖИМА (тот же пул + действие)
        $modeItems = @(
          ('[Полный]  — все роли ({0})' -f $pool.roles.Count),
          ('[Ведущий] — только {0}' -f $pool.lead),
          '[Выбрать вручную]'
        )
        $modeSel = Invoke-Fzf -Items $modeItems -Prompt 'Режим>' -Header ($verb + ' | Пул: ' + $pool.title + '  |  Esc — назад к действию')
        if (-not $modeSel) { break }                # Esc на режиме -> назад к выбору действия

        $selected = $null
        if ($modeSel.StartsWith('[Полный')) {
          $selected = @($pool.roles.owner)
        } elseif ($modeSel.StartsWith('[Ведущий')) {
          $selected = @($pool.lead)
        } else {
          $rmap = [ordered]@{}
          foreach ($r in $pool.roles) {
            $mark = if ($r.lead) { '  [лид]' } else { '' }
            $rmap[('{0}  ({1}){2}' -f $r.title, $r.owner, $mark)] = $r.owner
          }
          $rSel = Invoke-Fzf -Items ([string[]]$rmap.Keys) -Prompt 'Роли>' -Header ('TAB — отметить, Enter — ' + $verb + ', Esc — назад к режиму') -Multi
          if (-not $rSel) { continue }              # Esc на ролях -> назад к режиму
          $selected = @($rSel | ForEach-Object { $rmap[[string]$_] })
        }
        if (-not $selected) { continue }            # ничего не выбрано -> назад к режиму

        # ----- [Завершить]: контроллер в отдельном окне (killer pool-safe; -Only при подмножестве ролей) -----
        if ($isShutdown) {
          $allRoles = ($selected.Count -eq $pool.roles.Count)
          $scopeTxt = if ($allRoles) { 'ВЕСЬ пул' } else { ('роли: ' + ($selected -join ', ')) }
          $confSel = Invoke-Fzf -Items @(('[Да] завершить — ' + $scopeTxt), '[Отмена]') -Prompt 'Подтверди>' -Header ('Завершить "' + $pool.title + '"? ' + $scopeTxt)
          if (-not $confSel -or $confSel.StartsWith('[Отмена')) { continue }
          $shPs1  = Join-Path (Split-Path $Here -Parent) 'pool-bus\pool-shutdown.ps1'
          $psArgs = @('-NoProfile','-ExecutionPolicy','Bypass','-NoExit','-File',$shPs1,'-Pool',$pool.slug,'-Full','-CloseWindow')
          if (-not $allRoles) { $psArgs += @('-Only', ($selected -join ',')) }
          Start-Process 'powershell' -ArgumentList $psArgs
          Write-Host ('Завершение "{0}" запущено в отдельном окне ({1}). Compact-окна появятся отдельно.' -f $pool.title, $scopeTxt) -ForegroundColor Green
          Start-Sleep -Milliseconds 700
          break                                      # назад к выбору действия
        }

        # ----- [Запустить]: генерация Warp tab-config -----
        $toml    = New-PoolToml $pool $selected
        $cfgName = 'poollaunch-' + $pool.slug
        if (-not (Test-Path $TabCfg)) { New-Item -ItemType Directory -Force -Path $TabCfg | Out-Null }
        [System.IO.File]::WriteAllText((Join-Path $TabCfg ($cfgName + '.toml')), $toml, (New-Object System.Text.UTF8Encoding($false)))
        Start-Process ('warp://tab_config/{0}?new_window=true' -f $cfgName)

        if (-not $mru) { $mru = New-Object psobject }
        if ($mru.PSObject.Properties.Name -contains $pool.slug) { $mru.$($pool.slug) = (Get-Date).ToString('o') }
        else { $mru | Add-Member -NotePropertyName $pool.slug -NotePropertyValue ((Get-Date).ToString('o')) }
        Save-Mru $mru

        Write-Host ('Запущен пул "{0}". Роли: {1}' -f $pool.title, ($selected -join ', ')) -ForegroundColor Green
        Write-Host 'Пустые панели можно доднять в Warp: Ctrl-Shift-R -> имя роли.' -ForegroundColor DarkGray
        Start-Sleep -Milliseconds 700
        break                                        # после запуска -> назад к выбору действия
      }
    }
  }
}
catch {
  # Любая непредвиденная ошибка НЕ должна молча гасить окно — показываем и ждём Enter.
  Write-Host ''
  Write-Host ('[Pool Launcher] Непредвиденная ошибка: ' + $_.Exception.Message) -ForegroundColor Red
  Write-Host ('  ' + $_.InvocationInfo.PositionMessage) -ForegroundColor DarkGray
  Read-Host 'Нажми Enter, чтобы закрыть окно'
}
finally {
  if (Test-Path $PidF) { Remove-Item $PidF -Force -ErrorAction SilentlyContinue }
  if ($mtx) { try { $mtx.ReleaseMutex() } catch {}; $mtx.Dispose() }
}
